from CommunityBuilder.views.index import show_index
from CommunityBuilder.views.create_event import show_create
from CommunityBuilder.views.create_event import create_event
from CommunityBuilder.views.accounts import show_login
from CommunityBuilder.views.accounts import accounts_redirect
from CommunityBuilder.views.accounts import user_logout
from CommunityBuilder.views.eventdetails import show_event
from CommunityBuilder.views.users import show_user
from CommunityBuilder.views.map import show_map
from CommunityBuilder.views.edit_profile import show_edit